### ISSUE TITLE
This code can be used for S3DIS dataset?

### ISSUE THREAD

**Issue by Yellowshuohahaha** [lyqun/Task-Aware_Sampling#3]
It is a indoor semantic segmentation point cloud dataset.

**Comment by lyqun** [comment]
Yes. However, the improvements seem to be limited when adopting it in large scene segmentation; see the discussion in section 6.3.

**Comment by Yellowshuohahaha** [comment]
Thanks for your reply! I'm going to try this out and think about what else I can improve on.
